# src/CatalogBundle/Resources/config/doctrine/Product.orm.yml
CatalogCatalogBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
